name: trive

on: push

jobs:
    files:
        runs-on: ubuntu-latest

        steps:
            - name: create a one file
              run: echo "hi this ashok" > myfile 
            - name: updating time 
              run: echo date
                 
            
            
